x-airflow-common: &airflow-common
  image: apache/airflow:3.2.2
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://fraud_user:fraud_password@postgres:5432/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-api-server:8080/execution/
    AIRFLOW__API_AUTH__JWT_SECRET: fraud-project-secret
    DATABASE_URL: ${DATABASE_URL}
# Pour envoyer l'alerte par mail en cas de detection de fraude
    SMTP_HOST: ${SMTP_HOST}
    SMTP_PORT: ${SMTP_PORT}
    SMTP_USER: ${SMTP_USER}
    SMTP_PASSWORD: ${SMTP_PASSWORD}
    ALERT_EMAIL: ${ALERT_EMAIL}

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy


services:
  postgres:
    image: postgres:16
    container_name: fraud_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fraud_user"]
      interval: 5s
      timeout: 5s
      retries: 5


  api:
    build: .
    container_name: fraud_api
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  streamlit:
    build: .
    container_name: fraud_streamlit
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: streamlit run streamlit/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      postgres:
        condition: service_healthy

  
  airflow-init:
    <<: *airflow-common
    environment:
      <<: *airflow-common-env
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: airflow:admin
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: /tmp/airflow_simple_auth_passwords.json
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
    command: >
      bash -c 'printf "{\"airflow\":\"airflow\"}\n" > /tmp/airflow_simple_auth_passwords.json
      && airflow version'

  airflow-api-server:
    <<: *airflow-common
    environment:
      <<: *airflow-common-env
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: airflow:admin
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: /tmp/airflow_simple_auth_passwords.json
    command: >
      bash -c 'printf "{\"airflow\":\"airflow\"}\n" > /tmp/airflow_simple_auth_passwords.json
      && airflow api-server'
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    environment:
      <<: *airflow-common-env
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: airflow:admin
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: /tmp/airflow_simple_auth_passwords.json
    command: >
      bash -c 'printf "{\"airflow\":\"airflow\"}\n" > /tmp/airflow_simple_auth_passwords.json
      && airflow scheduler'

  airflow-dag-processor:
    <<: *airflow-common
    environment:
      <<: *airflow-common-env
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: airflow:admin
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: /tmp/airflow_simple_auth_passwords.json
    command: >
      bash -c 'printf "{\"airflow\":\"airflow\"}\n" > /tmp/airflow_simple_auth_passwords.json
      && airflow dag-processor'


volumes:
  postgres_data:
